services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  webapp:
    container_name: webapp
    image: blog-mongodb-api:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    profiles:
      - test
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/blog
    depends_on:
      - mongodb
volumes:
  mongo-data: {}
